openapi: 3.1.0
info:
  title: n8n Webhook (4e297216…)
  version: "1.0.0"
  description: |
    Trigger this n8n workflow by POSTing any JSON payload.
servers:
  - url: https://n8n.meiners.ipv64.net:8120
paths:
  /webhook/4e297216-53e7-4e2a-a93b-2709cd6fc8a9:
    post:
      operationId: sendToN8n
      summary: Sendet Daten an den n8n‑Workflow
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Beliebige Schlüssel/Wert‑Daten, die das Workflow‑Node erwartet
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
